apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: registry.saas.hand-china.com/scdf/rabbitmq:3.6.10
        name: rabbitmq
        ports:
        - containerPort: 5672
